name: adjflows
channels:
  - conda-forge
  - defaults
dependencies:
  - pytz
  - openmpi
  - pandas
  - scipy
  - python-dateutil
  - numpy
  - pip
  - python
  - wheel
  - mpi4py
  - setuptools
  - pyyaml
  - netcdf4
  - ipykernel
  - xarray
  - packaging
  - pygmt
  - pyproj
  - vtk
prefix: /home/harry/.conda/envs/adjflows
